# Generated by Django 3.0.3 on 2020-03-27 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('premium', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'premium field should be an interger number greater than Zero.')])),
                ('cover', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'cover field should be an interger number greater than Zero.')])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer')),
            ],
            options={
                'db_table': 'insurance_policy',
            },
        ),
    ]
