# Generated by Django 3.0.3 on 2020-03-26 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('premium', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'premium field should be an interger number greater than Zero.')])),
                ('cover', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'cover field should be an interger number greater than Zero.')])),
            ],
            options={
                'db_table': 'insurance_policy',
            },
        ),
    ]
