# Generated by Django 3.0.3 on 2020-03-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('insurance_policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='customer_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
            preserve_default=False,
        ),
    ]
