# Generated by Django 3.0.3 on 2020-03-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_policy', '0002_insurancepolicy_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
